#!/bin/bash

set -e

if [ $(whoami) == "root" ]; then
    echo "Do not run as root!" 1>&2
    exit 1
fi

GCE_PROJECT="rancher-dev"

dir=$(dirname $0)
source ${dir}/lib/user_data_clusters

gcloud -v >/dev/null 2>&1 || {
    echo "gcloud command not found." 1>&2
    exit 1
}

print_help()
{
    cat 1>&2 <<EOF
gce-10acre-ranch Usage:
    gce-10acre-ranch [opts] 
    -a - Agent Container:
            needs full container repo/name[:tag]
    -b - Build a new cluster
    -c - Cluster name[Required]
    -d - DELETE ALL NODES
    -i - Show the IP address of the master
    -h - Print this message
    -l - List nodes or clusters if no -c is passed
    -n - Number of nodes 
    -s - Server Container:
            needs full container repo/name[:tag] 
    -o - OS image
           centos-7
           coreos-alpha
           coreos-beta
           coreos-stable
           fedora-21
           ubuntu
    -p - privileged agent (needed for fedora)
    -q - Do not prompt user
EOF
}

while getopts ":a:bc:dhiln:o:ps:q" opt;do
    case $opt in
    a)
        AGENT_CONTAINER="${OPTARG}"
        ;;
    b)
        BUILD_CLUSTER_FLAG="true"
        ;;
    c)
        # Add 10acre so that you can't accidentally list/delete lots of hosts easily.
        CLUSTER_NAME="${OPTARG}-10acre"
        MASTER_NAME="${CLUSTER_NAME}-master-0"
        ;;
    d)
        DELETE_NODES_FLAG="true"
        ;;
    h)
        print_help
        exit 1
        ;;
    i)
        MASTER_IP_FLAG="true"
        ;;
    l)
        LIST_NODES_FLAG="true"
        ;;
    n)
        INSTANCE_COUNT=${OPTARG}
        ;;
    o)
        OS_FAMILY=${OPTARG}
        ;;
    p)
        PRIVILEGED_AGENT="true"
        ;;
    s)
        SERVER_CONTAINER="${OPTARG}"
        ;;
    q)
        QUIET="true"
        ;;
    \?)
        echo "Invalid arguemnts" >&2
        print_help
        exit 1
        ;;
    :)
        echo "Option -${OPTARG} requires arguement." >&2
        print_help
        exit 1
        ;;
    esac
done
shift $((OPTIND-1))

validate_vars()
{
    if [[ -z ${CLUSTER_NAME} && "${LIST_NODES_FLAG}" != "true" ]]; then
        echo "Need to specify cluster name" >&2
        print_help
        exit 1
    fi
    if [[ -z ${INSTANCE_COUNT} && "${BUILD_CLUSTER_FLAG}" == "true" ]]; then
        echo "Please specify number of nodes with -n" >&2
        print_help
        exit 1
    fi
}

list_nodes()
{
    local opts

    if [ -n "${CLUSTER_NAME}" ]; then
        opts="--regex \"${CLUSTER_NAME}.*\""
    fi

    gcloud compute instances list --project ${GCE_PROJECT} --zone us-central1-f ${opts}
}

delete_nodes()
{
    local opts
    local nodes

    nodes=$(list_nodes | grep -v ^NAME | cut -d' ' -f1)

    # This will prompt the user to confirm.
    if [ ${QUIET} ]; then
        opts="--quiet"
    else
        opts=""
    fi

    gcloud compute instances delete ${opts} --project ${GCE_PROJECT} --zone us-central1-f ${nodes}
}

get_master_ip()
{
    IP=$(gcloud compute instances describe "${MASTER_NAME}" --project ${GCE_PROJECT} --zone us-central1-f | grep natIP | cut -d':' -f2)
    echo $IP
}

get_os_image()
{
    local image

    # Has to be a better more dynamic way...that also isn't slow.
    case $OS_FAMILY in
        "ubuntu")
            image="ubuntu-14-04"
            ;;
        "coreos-alpha")
            image="https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/coreos-alpha-509-1-0-v20141124"
            ;;
        "coreos-beta")
            image="https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/coreos-beta-494-1-0-v20141124"
            ;;
        "coreos-stable")
            image="coreos"
            ;;
        "centos-7")
            image="centos-7"
            ;;
        "fedora-21")
            image="fedora-cloud-base-21-20141217"
            ;;
        *)
            image="ubuntu-14-04"
            ;;
    esac

    echo "${image}"

}

get_user_data_flag()
{
    case $OS_FAMILY in
        "fedora-21")
            echo "true"
            ;;
        *)
            echo "false"
            ;;
    esac
}

gcloud_create()
{
    # 1 - instance name
    # 2 - startup script path/filename
    # 3 - GCE tags

    local metadata_key=startup-script

    if [ "$(get_user_data_flag)" = "true" ]; then
        metadata_key=user-data
    fi

    gcloud compute instances create ${1} \
        --zone "us-central1-f" --machine-type "n1-standard-1" \
        --network "default" \
        --project "${GCE_PROJECT}" \
        --metadata-from-file ${metadata_key}=${2} \
        --maintenance-policy "MIGRATE" \
        --scopes "https://www.googleapis.com/auth/devstorage.read_only" \
        --tags ${3} \
        --image $(get_os_image)
}


generate_build_script() # signature: role container
{
    local container
    local default_container
    local build_file
    local docker_opts
    local docker_cmd

    case $1 in
        master)
            default_container="rancher/server"

            docker_opts=('"run"', '"-d"', '"-p"', '"8080:8080"');
            build_file="/tmp/10acre-master-build.sh"
            docker_cmd=
            ;;
        worker)
            default_container="rancher/agent"

            IP=$(get_master_ip)
            docker_opts=('"run"', '"-d"', '"-v"', '"/var/run/docker.sock:/var/run/docker.sock"');

            if [[ "${PRIVILEGED_AGENT}" = "true" ]]; then
                docker_opts+=(, '"--privileged"')
            fi

            docker_cmd="http://${IP}:8080"
            build_file="/tmp/10acre-worker-build.sh"
            ;;
        *)
            echo "Can not generate build script"
            exit 1
            ;;
    esac

    if [ -z ${2} ]; then
        container=${default_container}
    else
        container="${2}"
    fi

    if [ "$(get_user_data_flag)" = "true" ]; then
        user_data_clusters $(id -un) "$(cat ~/.ssh/id_rsa.pub)" ${build_file} "${container}" docker_opts[@] "${docker_cmd}"
    else
            cat > ${build_file} << EOF
#!/bin/bash

curl -sSL --retry 5 --retry-delay 10 https://get.docker.com/| sh
sleep 5
docker $(echo ${docker_opts[@]}| sed -e 's/,//g'|sed -e 's/\"//g') ${container} ${docker_cmd}
EOF
    fi

}

build_master()
{
    generate_build_script "master" "${SERVER_CONTAINER}"
    gcloud_create "${MASTER_NAME}" "/tmp/10acre-master-build.sh" "alt-http-server"
}

build_compute()
{
    local instances
    
    for i in $(seq 1 ${INSTANCE_COUNT}); do
        instances="${CLUSTER_NAME}-${i} ${instances}"
    done

    generate_build_script "worker" "${AGENT_CONTAINER}"
    gcloud_create "${instances}" "/tmp/10acre-worker-build.sh" "alt-http-server open-compute-nodes"
}

build_cluster()
{
    build_master
    build_compute
}

main() 
{
    validate_vars
    if [[ "${LIST_NODES_FLAG}" = "true" && -z "$CLUSTER_NAME" ]]; then
        list_nodes | grep -- '-master-' | sed -e 's/^\(.*\)\(-10acre-master.*\)$/\1/' | sort -u
    elif [ "${LIST_NODES_FLAG}" = "true" ]; then
        list_nodes 
    elif [ "${MASTER_IP_FLAG}" = "true" ]; then
        get_master_ip
    elif [ "${DELETE_NODES_FLAG}" = "true" ]; then 
        delete_nodes
    elif [ "${BUILD_CLUSTER_FLAG}" = "true" ]; then
        build_cluster
    fi
}

main
